/**
 * Etiquetas legibles de los campos extraídos (mismas que usa el frontend en
 * frontend/src/lib/ui.ts). El orden de las claves define el orden de despliegue.
 */
export const ETIQUETAS: Record<string, string> = {
  nombre_completo: 'Nombre completo',
  nombres: 'Nombre(s)',
  primer_apellido: 'Primer apellido',
  segundo_apellido: 'Segundo apellido',
  curp: 'CURP',
  fecha_nacimiento: 'Fecha de nacimiento',
  sexo: 'Sexo (H/M)',
  clave_elector: 'Clave de elector',
  domicilio: 'Domicilio',
  domicilio_calle: 'Calle y número',
  domicilio_colonia: 'Colonia y C.P.',
  domicilio_municipio_ciudad: 'Municipio / ciudad',
  estado: 'Estado (código)',
  municipio: 'Municipio (código)',
  localidad: 'Localidad',
  seccion: 'Sección',
  año_registro: 'Año de registro',
  año_emision: 'Año de emisión',
  año_vigencia: 'Año de vigencia',
  folio_impresion: 'Folio de impresión',
  identificador_electronico: 'Identificador electrónico',
  numero_certificado_nac: 'No. certificado de nacimiento',
  numero_acta: 'Número de acta',
  entidad_registro: 'Entidad de registro',
  municipio_registro: 'Municipio de registro',
  fecha_registro: 'Fecha de registro',
  oficialia: 'Oficialía',
  libro: 'Libro',
  lugar_nacimiento: 'Lugar de nacimiento',
  nombre_padre: 'Nombre del padre',
  primer_apellido_padre: 'Primer apellido del padre',
  segundo_apellido_padre: 'Segundo apellido del padre',
  nacionalidad_padre: 'Nacionalidad del padre',
  curp_padre: 'CURP del padre',
  nombre_madre: 'Nombre de la madre',
  primer_apellido_madre: 'Primer apellido de la madre',
  segundo_apellido_madre: 'Segundo apellido de la madre',
  nacionalidad_madre: 'Nacionalidad de la madre',
  curp_madre: 'CURP de la madre',
  numero_pasaporte: 'Número de pasaporte',
  tipo_pasaporte: 'Tipo',
  pais_expedicion: 'País de expedición',
  nacionalidad: 'Nacionalidad',
  fecha_expedicion: 'Fecha de expedición',
  fecha_caducidad: 'Fecha de caducidad',
  mrz_linea1: 'MRZ línea 1',
  mrz_linea2: 'MRZ línea 2',
  observaciones: 'Observaciones',
  fecha_inscripcion: 'Fecha de inscripción',
  folio: 'Folio',
  curps_asociadas: 'CURPs asociadas',
  codigo_verificacion: 'Código de verificación',
  fecha_emision: 'Fecha de emisión de la constancia',
};

export const etiqueta = (campo: string) => ETIQUETAS[campo] ?? campo.replace(/_/g, ' ');
export const ORDEN_CAMPOS = Object.keys(ETIQUETAS);
